version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: compile modules and packages-app
          command: npm run build:big-fat-test
      - run:
          name: ng test
          command: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
